# Generated by Django 3.0.7 on 2020-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='QType',
            field=models.CharField(choices=[('TE', 'Text'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice')], default='TE', max_length=2),
        ),
    ]
