# Generated by Django 3.0.7 on 2020-06-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200618_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
    ]
