# Generated by Django 3.0.7 on 2020-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200619_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='QType',
            field=models.CharField(choices=[('TE', 'Text'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice')], default='TE', max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.TextField(),
        ),
    ]
